package com.consulting.service;

import com.consulting.constants.Role;
import com.consulting.dto.UserCreateRequest;
import com.consulting.dto.UserUpdateRequest;
import com.consulting.model.User;
import com.consulting.repository.UserRepository;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Set;

@Service
@Transactional
public class UserServiceImpl implements UserService {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder; // Add this

    public UserServiceImpl(UserRepository userRepository, PasswordEncoder passwordEncoder) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder; // Initialize
    }

    @Override
    public User createUser(UserCreateRequest userCreateRequest) {
        // Check if email already exists
        if (existsByEmail(userCreateRequest.getUserEmailId())) {
            throw new IllegalArgumentException("User with email " + userCreateRequest.getUserEmailId() + " already exists");
        }

        // Validate roles
        validateRoles(userCreateRequest.getRoles());

        // Create new user
        User user = new User();
        user.setUserEmailId(userCreateRequest.getUserEmailId());
        user.setUserName(userCreateRequest.getUserName());

        // **CRITICAL FIX: Encode password before saving**
        user.setPassword(passwordEncoder.encode(userCreateRequest.getPassword()));

        // Set roles
        user.setRoles(userCreateRequest.getRoles());

        // Save user (ID will be auto-generated by @PrePersist)
        return userRepository.save(user);
    }

    @Override
    @Transactional(readOnly = true)
    public User getUserById(String userId) {
        return userRepository.findById(userId)
                .orElseThrow(() -> new IllegalArgumentException("User not found with ID: " + userId));
    }

    @Override
    @Transactional(readOnly = true)
    public User getUserByEmail(String email) {
        return userRepository.findAll().stream()
                .filter(user -> email.equalsIgnoreCase(user.getUserEmailId()))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("User not found with email: " + email));
    }

    @Override
    @Transactional(readOnly = true)
    public List<User> getAllUsers() {
        return userRepository.findAll();
    }

    @Override
    public User updateUser(String userId, UserUpdateRequest updateRequest) {
        User user = getUserById(userId);

        // Update email if provided and not already taken
        if (updateRequest.getUserEmailId() != null &&
                !updateRequest.getUserEmailId().equals(user.getUserEmailId())) {

            if (existsByEmail(updateRequest.getUserEmailId())) {
                throw new IllegalArgumentException("Email " + updateRequest.getUserEmailId() + " is already in use");
            }
            user.setUserEmailId(updateRequest.getUserEmailId());
        }

        // Update name if provided
        if (updateRequest.getUserName() != null) {
            user.setUserName(updateRequest.getUserName());
        }

        return userRepository.save(user);
    }

    @Override
    public User updatePassword(String userId, String newPassword) {
        User user = getUserById(userId);

        // **FIX: Encode new password before saving**
        user.setPassword(passwordEncoder.encode(newPassword));

        return userRepository.save(user);
    }

    @Override
    public void deleteUser(String userId) {
        // Check if user exists
        if (!userRepository.existsById(userId)) {
            throw new IllegalArgumentException("User not found with ID: " + userId);
        }

        userRepository.deleteById(userId);
    }

    @Override
    @Transactional(readOnly = true)
    public boolean existsByEmail(String email) {
        return userRepository.findAll().stream()
                .anyMatch(user -> email.equalsIgnoreCase(user.getUserEmailId()));
    }

    @Override
    @Transactional(readOnly = true)
    public List<User> getUsersByRole(String role) {
        // Convert string to Role enum
        Role roleEnum;
        try {
            roleEnum = Role.valueOf(role.toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Invalid role: " + role);
        }

        return userRepository.findAll().stream()
                .filter(user -> user.getRoles() != null && user.getRoles().contains(roleEnum))
                .toList();
    }

    // Helper method to validate roles
    private void validateRoles(Set<Role> roles) {
        if (roles == null || roles.isEmpty()) {
            throw new IllegalArgumentException("User must have at least one role");
        }

        // Add any additional role validation logic here
        for (Role role : roles) {
            if (role == null) {
                throw new IllegalArgumentException("Role cannot be null");
            }
        }
    }

    // Additional helper methods
    @Transactional(readOnly = true)
    public long getTotalUserCount() {
        return userRepository.count();
    }

    public User assignAdditionalRole(String userId, Role newRole) {
        User user = getUserById(userId);

        Set<Role> roles = user.getRoles();
        if (roles == null) {
            roles = Set.of(newRole);
        } else {
            roles.add(newRole);
        }

        user.setRoles(roles);
        return userRepository.save(user);
    }

    public User removeRole(String userId, Role roleToRemove) {
        User user = getUserById(userId);

        Set<Role> roles = user.getRoles();
        if (roles != null && !roles.isEmpty()) {
            roles.remove(roleToRemove);

            // Ensure user has at least one role
            if (roles.isEmpty()) {
                throw new IllegalArgumentException("User must have at least one role");
            }

            user.setRoles(roles);
        }

        return userRepository.save(user);
    }

    // **FIXED: authenticateUser method - Compare encoded passwords**
    @Transactional(readOnly = true)
    public User authenticateUser(String email, String password) {
        User user = userRepository.findAll().stream()
                .filter(u -> email.equalsIgnoreCase(u.getUserEmailId()))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("Invalid email or password"));

        // Compare encoded password with provided password
        if (passwordEncoder.matches(password, user.getPassword())) {
            return user;
        } else {
            throw new IllegalArgumentException("Invalid email or password");
        }
    }

    // **FIXED: updateUserFull method - Encode password if provided**
    public User updateUserFull(String userId, UserUpdateRequest updateRequest, String newPassword, Set<Role> newRoles) {
        User user = getUserById(userId);

        // Update email if provided
        if (updateRequest.getUserEmailId() != null &&
                !updateRequest.getUserEmailId().equals(user.getUserEmailId())) {

            if (existsByEmail(updateRequest.getUserEmailId())) {
                throw new IllegalArgumentException("Email " + updateRequest.getUserEmailId() + " is already in use");
            }
            user.setUserEmailId(updateRequest.getUserEmailId());
        }

        // Update name if provided
        if (updateRequest.getUserName() != null) {
            user.setUserName(updateRequest.getUserName());
        }

        // **FIX: Encode password if provided**
        if (newPassword != null && !newPassword.trim().isEmpty()) {
            user.setPassword(passwordEncoder.encode(newPassword));
        }

        // Update roles if provided
        if (newRoles != null && !newRoles.isEmpty()) {
            validateRoles(newRoles);
            user.setRoles(newRoles);
        }

        return userRepository.save(user);
    }

    // New method: Check if user has specific role
    @Transactional(readOnly = true)
    public boolean hasRole(String userId, String role) {
        try {
            Role roleEnum = Role.valueOf(role.toUpperCase());
            User user = getUserById(userId);
            return user.getRoles() != null && user.getRoles().contains(roleEnum);
        } catch (IllegalArgumentException e) {
            return false;
        }
    }

    // **NEW: Add this method to your UserService interface as well**
    @Transactional(readOnly = true)
    public User findByEmail(String email) {
        return userRepository.findAll().stream()
                .filter(user -> email.equalsIgnoreCase(user.getUserEmailId()))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("User not found with email: " + email));
    }
}